Repository Awesome-SomeOne/awesome-client-web, pull requests merged in 2024-09, with the labels that each got.

#56 Yoon/#55 공통 컴포넌트 수정
  src/components/common/chip/index.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/dropdown/styles.ts
  src/components/common/generalHeader/index.tsx
  src/components/common/textLabel/styles.ts
Labels: Fix, Design, 👩‍💻서윤

#57 Sol/#48 [style]: 커뮤니티 랜딩 페이지 퍼블리싱
  src/assets/icons/HeartIcon.svg
  src/assets/icons/SaveIcon.svg
  src/assets/icons/SearchIcon.tsx
  src/assets/icons/SpeechBubble.svg
  src/components/common/fullPageModal/index.tsx
  src/components/community/CardForPost/index.tsx
  src/components/community/CardForPost/styles.ts
  src/components/community/MyActivityRecord/index.tsx
  src/components/community/MyActivityRecord/styles.ts
  src/components/community/PopularMemory/index.tsx
  src/components/community/PopularMemory/styles.ts
  src/components/community/PostList/index.tsx
  src/components/community/PostList/styles.ts
  src/constants/path.ts
  src/pages/community/CommunityPage.tsx
  src/pages/community/styles.ts
  src/routes/AppRouter.tsx
Labels: Design, 👩‍💻솔미

#61 선우#60 추억 모아보기 페이지 퍼블리싱
  src/assets/icons/ToggleButton.tsx
  src/assets/images/ImageMarker/DefaultImageMarker.svg
  src/assets/images/ImageMarker/SelectedImageMarker.svg
  src/assets/images/mockImage1.png
  src/assets/images/mockImage2.png
  src/components/myTripRecordList/RecordCard.tsx
  src/components/myTripRecordList/styles.ts
  src/constants/path.ts
  src/data/dummy-marker.ts
  src/models/marker.ts
  src/pages/myTripRecordList/CustomMarker.tsx
  src/pages/myTripRecordList/MyTripRecordList.tsx
  src/pages/myTripRecordList/styles.ts
  src/routes/AppRouter.tsx
Labels: Design, 👨‍💻선우

#64 💄 Fix: 내여행 bottom section height
  src/components/myTrip/plan/styles.ts
  src/components/myTrip/planGenerating/index.tsx
  src/components/myTrip/planGenerating/styles.ts
Labels: Fix, Design, 👩‍💻서윤

#65 ✨ Feat: 홈 > 위치 바꾸기
  src/components/home/CurrentLoaction/index.tsx
  src/pages/home/HomePage.tsx
  src/pages/home/location/LocationPage.tsx
  src/pages/home/location/styles.ts
Labels: Feat, Design, 👩‍💻서윤

#74 Yoon/#62 planAtom 생성, 거리 계산 추가, api 사용 등 코드 수정
  package-lock.json
  package.json
  src/apis/myTrip/myTrip.queries.ts
  src/assets/images/place_null.svg
  src/atoms/myTrip/planAtom.ts
  src/components/home/DetailPage/index.tsx
  src/components/home/Notification/index.tsx
  src/components/home/Notification/styles.ts
  src/components/home/PopularPlace/index.tsx
  src/components/home/RecommendPlace/index.tsx
  src/components/myTrip/inputComponent/index.tsx
  src/components/myTrip/inputComponent/styles.ts
  src/components/myTrip/listComponent/index.tsx
  src/components/myTrip/plan/index.tsx
  src/components/myTrip/planGenerating/index.tsx
  src/constants/homePageConstants.ts
  src/pages/home/detail/report/ReportPage.tsx
  src/pages/home/like/LikePage.tsx
  src/pages/home/popularPlace/PopularPlacePage.tsx
  src/pages/home/recommendPlace/RecommendPlacePage.tsx
  src/pages/home/search/SearchPage.tsx
  src/pages/home/search/SearchResultPage.tsx
  src/pages/myTrip/MyTripPage.tsx
  src/pages/myTrip/addPlace/AddPlacePage.tsx
  src/pages/myTrip/editPlan/EditPlanPage.tsx
  src/pages/myTrip/generatePlan/GeneratePlanPage.tsx
  src/pages/myTrip/plan/PlanPage.tsx
  src/pages/myTrip/tripIsland/TripIslandPage.tsx
  src/pages/myTrip/tripIsland/recommendationIsland/RecommendedIsland.tsx
  src/pages/myTrip/tripIsland/search/TripIslandSearchPage.tsx
  src/pages/myTrip/tripSchedule/TripSchedulePage.tsx
  src/pages/myTrip/tripTheme/TripThemePage.tsx
  src/pages/myTrip/tripTheme/styles.ts
  src/types/myTrip.ts
  src/utils/myTrip/myTrip.utils.ts
Labels: Chore, Feat, 👩‍💻서윤

#84 선우#79 마이페이지 추가
  src/assets/images/kakao.png
  src/components/common/bottomNavBar/index.tsx
  src/components/common/toggle/index.tsx
  src/components/common/toggle/styles.ts
  src/components/myPage/index.tsx
  src/components/myPage/styles.ts
  src/constants/path.ts
  src/pages/myPage/AccountInfoPage/AccountInfoPage.tsx
  src/pages/myPage/AccountInfoPage/styles.ts
  src/pages/myPage/ContactPage/ContactPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/MyReviewPage/MyReviewPage.tsx
  src/pages/myPage/MyReviewPage/styles.ts
  src/pages/myPage/NotificationSettingPage/NotificationSettingPage.tsx
  src/pages/myPage/NotificationSettingPage/styles.ts
  src/pages/myPage/SettingProfile.tsx
  src/pages/myPage/TermsPage/TermsPage.tsx
  src/pages/myPage/styles.ts
  src/routes/AppRouter.tsx
Labels: Feat, Design, 👨‍💻선우
