Repository Awesome-SomeOne/awesome-client-web, pull requests merged in 2024-08, with the labels that each got.

#42 Sol/#41 full page modal 공통 컴포넌트 추가
  src/assets/icons/BellIcon.tsx
  src/assets/icons/Clear.tsx
  src/assets/icons/ClearIcon.tsx
  src/assets/icons/MoreIcon.tsx
  src/components/common/fullPageModal/index.tsx
  src/components/common/fullPageModal/styles.ts
  src/components/common/textArea/styles.ts
  src/components/myTripRecord/ReviewFullPageModal/index.tsx
  src/components/myTripRecord/ReviewFullPageModal/styles.ts
  src/components/myTripRecord/SpotCard/index.tsx
Labels: Feat

#44 Sol/#43 별점 등록 공통 컴포넌트 & 단계 표시용 공통 컴포넌트 생성
  src/assets/icons/StarIcon.tsx
  src/components/common/chip/index.tsx
  src/components/common/fullPageModal/index.tsx
  src/components/common/fullPageModal/styles.ts
  src/components/common/orderDisplayCircleChips/index.tsx
  src/components/common/searchBar/index.tsx
  src/components/common/searchBar/styles.ts
  src/components/common/starRate/index.tsx
  src/components/common/starRate/starRateContext.tsx
  src/components/myTripRecord/DetailSchedule/index.tsx
  src/components/myTripRecord/DetailSchedule/styles.ts
  src/components/myTripRecord/DetailTravelMemories/index.tsx
  src/components/myTripRecord/DetailTravelMemories/styles.ts
  src/components/myTripRecord/ReviewFullPageModal/index.tsx
  src/components/myTripRecord/ReviewFullPageModal/styles.ts
  src/components/myTripRecord/SpotCard/index.tsx
  src/pages/myTripList/styles.ts
  src/pages/myTripRecord/MyTripRecordPage.tsx
  src/pages/myTripRecord/styles.ts
  src/pages/myTripRecordDetail/MyTripRecordDetailPage.tsx
  src/pages/myTripRecordDetail/styles.ts
Labels: Feat, Design, 👩‍💻솔미

#54 Yoon/#52 공통 컴포넌트, 아이콘 수정, theme color 추가
  src/assets/icons/BackIcon.svg
  src/assets/icons/ClearIcon.tsx
  src/assets/icons/DropdownIcon.tsx
  src/components/common/bottomSheet/styles.ts
  src/components/common/chip/index.tsx
  src/components/common/chip/styles.ts
  src/components/common/dropdown/index.tsx
  src/components/common/generalHeader/index.tsx
  src/components/common/generalHeader/styles.ts
  src/components/common/header/styles.ts
  src/components/common/searchBar/index.tsx
  src/components/common/searchBar/styles.ts
  src/components/common/simpleModal/styles.ts
  src/components/common/tabAnatomy/index.tsx
  src/styles/theme.ts
Labels: Fix, Design, 👩‍💻서윤
